name: Node.js CI

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: yarn install
      - run: npx pm2 start app.js
      - run: node test-app.js
      - run: npx pm2 logs --nostream && npx pm2 delete all
        if: always()
