name: Node.js CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: yarn install
    - run: npx pm2 start app.js
    - uses: indiesdev/curl@v1
      with:
        url: http://localhost:3000
        method: 'GET'
        accept: 200
        headers: '{ "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36" }'
        timeout: 1000
        is_debug: true
    - run: npx pm2 logs --nostream && npx pm2 delete all
      if: always()
